### PR TITLE
rare loot fix

### PR DESCRIPTION
**Pull request by Johnmatic**
better rare loot respawn, magazines if rare loot is weapon

### CODE REVIEW

**Comment by Johnmatic** [comment]
Sorry for short description. With this fix rare loot will respawn in count of 0-rarelootcount. Instead of 0 or rarelootcount. It will also try to respawn magazines if chosen rare loot has any.

**Comment by eraser1** [comment]
@Johnmatic Nice work! Definitely one of the things I overlooked after initial implementation.

I do have a request though: Can you change the merge request to the [testing branch](https://github.com/Defent/DMS_Exile/tree/Testing) instead of the main branch?

**Comment by Johnmatic** [comment]
done, sorry for the delay

**Comment by ice19942335** [comment]
Please merge =)

**Pull request merged**
